---
title: "Periodo frazionario"
author: "Thomas"
date: "2023-08-17"
output:
  #pdf_document: 
  #fig_crop: false
  word_document:
  fig_crop: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center')
```

```{r functions, include=FALSE}
##
## raccolta di funzioni utili
##

library(ggplot2)
library(dplyr)
library(grid)
library(gridExtra)
library(scales)
results <-read.csv("results.csv")

## plotta una singola run 
smallPlotRun<-function(idRun){
  
  runDataSet= filter(results,Run == idRun)
  
  # Creazione del grafico a pallini
  ggplot(runDataSet, 
         aes(x = String.Length, 
             y = Duration, 
             color = Algorithm.Type)) +
    
    geom_point() +
    
    scale_color_manual(values = c("naive" = "red", 
                                  "smart" = "blue")) +
    
    scale_y_continuous(
      labels = scientific_format(),  # Imposta i label in notazione esponenziale
      
    ) +
    scale_x_continuous(
      labels = scientific_format(),  # Imposta i label in notazione esponenziale
      
    )+
    
    labs(
      x= "Lunghezza stringa (caratteri)",
      y="Durata (ns)"
    )+
    
    theme(legend.position="none")
  
}
#####

## Calcola la media delle run
## ritorna dataset con 2 colonne: string.Length, Duration
## Duration è la media delle run
average <-function(algo){
  # Filtra i risultati per l'algoritmo "naive"
  algo_results <- results %>%
    filter(Algorithm.Type == algo)
  
  # Imposta l'opzione per la notazione esponenziale
  options(scipen = 999)
  
  # Raggruppa per lunghezza della stringa e calcola la media della durata
  average_duration_by_length <- algo_results %>%
    group_by(String.Length) %>%
    summarise(Duration = mean(Duration))
  
  return (average_duration_by_length)
}
#####
```

```{r 6runs , echo=FALSE}
##
## plot delle 5 run di raccolta dati eseguite
##
run1<- smallPlotRun(1)
run2<- smallPlotRun(2)
run3<- smallPlotRun(3)
run4<- smallPlotRun(4)
run5<- smallPlotRun(5)
run6<- smallPlotRun(6)

Layout_Grafici <- grid.arrange(run1, run2, run3, run4, run5, run6,
                               ncol = 2, nrow = 3,
                               top = textGrob("Durata vs Lunghezza della stringa"))

#plot(layout_grafici)
```


```{r averagerun,  fig.width=6, echo=FALSE}
naive <- average("naive")
smart <- average("smart")

# Aggiungi le informazioni calcolate al dataset "results"
results <- bind_rows(
  results,
  mutate(naive, 
         Algorithm.Type =  "naive",
         Fractional.Period = NA,
         Run = 0)
)

results <- bind_rows(
  results,
  mutate(smart, 
         Algorithm.Type =  "smart",
         Fractional.Period = NA,
         Run = 0)
)

## plotta la media
average_results <- filter(results, Run == 0)

Durata_VS_Lunghezza<-
  ggplot(average_results, 
         aes(x = String.Length, 
             y = Duration, 
             color = Algorithm.Type)) +
  
  geom_point() +
  
  scale_color_manual(values = c("naive" = "red", 
                                "smart" = "blue")) +
  
  scale_y_continuous(
    labels = scientific_format(),  # Imposta i label in notazione esponenziale
  ) +
  
  scale_x_continuous(
    labels = scientific_format(),  # Imposta i label in notazione esponenziale
  ) +
  
  labs(title = "Durata vs Lunghezza della stringa (scala logaritmica)",
       x= "Lunghezza stringa (caratteri)",
       y="Durata (nanosecondi)",
       color = "Algoritmo")
#plot(Durata_VS_Lunghezza)
```


```{r previsionsNaive , echo=FALSE}

naiveRegression= lm(Duration ~ poly(String.Length, 2, raw=TRUE), data = naive )
naiveRegressionSummary=summary(naiveRegression)
coefficenti_naive<-coef(naiveRegression)

Previsone_Naive<-
  ggplot(naive, 
         aes(x = String.Length, 
             y = Duration
         )) +
  
  geom_point(color='red') +
  
  stat_smooth( method = "lm", 
               formula = y ~ poly(x, 2, raw = TRUE), 
               se=TRUE, fill=NA,
               colour="black"
  )+
  
  scale_y_continuous(
    labels = scientific_format(),  # Imposta i label in notazione esponenziale
  ) +
  scale_x_continuous(
    labels = scientific_format(),  # Imposta i label in notazione esponenziale
  )+
  
  labs(title = "Modello previsione algoritmo Naive",
       x= "Lunghezza stringa",
       y="Durata (nanosecondi)"
  )

#plot(Previsone_Naive)

```


```{r previsionssmart , echo=FALSE}

smartRegression=lm(Duration ~ String.Length, data = smart)
smartRegressionSummary= summary(smartRegression)
coefficenti_smart<-coef(smartRegression)

Previsione_Smart<- 
  ggplot(smart, 
         aes(x = String.Length, 
             y = Duration
         )) +
  
  geom_point(color='blue') +
  
  geom_smooth(method = "lm",formula = "y ~ x", se = FALSE, color = "black") +
  
  scale_y_continuous(
    labels = scientific_format(),  # Imposta i label in notazione esponenziale
    
  ) +
  scale_x_continuous(
    labels = scientific_format(),  # Imposta i label in notazione esponenziale
    
  )+
  
  labs(title = "Modello previsione algoritmo Smart",
       x= "Lunghezza stringa",
       y="Durata (nanosecondi)"
  )

#plot(Previsione_Smart)
```