---
title: "Periodo frazionario"
author: "Thomas Massarutto"
date: "2023-08-17"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r functions, include=FALSE}
##
## raccolta di funzioni utili
##

library(ggplot2)
library(dplyr)
library(gridExtra)
results <-read.csv("results2.csv")

plotrun<-function(idRun){
  
  runDataSet= filter(results,Run == idRun)
  
  # Creazione del grafico a pallini
  ggplot(runDataSet, 
         aes(x = String.Length, 
             y = Duration, 
             color = Algorithm.Type)) +
    
    geom_point() +
    
    scale_color_manual(values = c("naive" = "red", 
                                  "smart" = "blue")) +
    
    labs(title = "Durata vs Lunghezza della stringa",
         x= "Lunghezza della stringa",
         y="Durata (nanosecondi)",
         color = "Tipologia di Algoritmo")
  
}
#####

average <-function(algo){
  # Filtra i risultati per l'algoritmo "naive"
  algo_results <- results %>%
    filter(Algorithm.Type == algo)
  
  # Imposta l'opzione per la notazione esponenziale
  options(scipen = 999)
  
  # Raggruppa per lunghezza della stringa e calcola la media della durata
  average_duration_by_length <- algo_results %>%
    group_by(String.Length) %>%
    summarise(avg_duration = mean(Duration))
  
  return (average_duration_by_length)
}
#####

# Definizione della funzione per il plot delle prime 20 righe
plot_first_30 <- function(data, point_color) {
  # Prende solo le prime 20 righe
  subset_data <- head(data, 30)
  
  # Creazione del grafico
  ggplot(subset_data, aes(x = String.Length, y = avg_duration)) +
    geom_point(color = point_color) +
    labs(title = "Primi 30 dati: Durata media vs Lunghezza della stringa",
         x = "Lunghezza della stringa",
         y = "Durata media")
}

```


```{r 5runs , echo=FALSE}
##
## plot delle di raccolta dati eseguite
##
plotrun(1)
plotrun(2)
plotrun(3)
plotrun(4)
plotrun(5)
plotrun(6)

```

```{r averagerun, echo=FALSE}
naive <- average("naive")
smart <- average("smart")
summary(naive)
summary(smart)


# Creazione del grafico a pallini
ggplot(naive, 
       aes(x = String.Length, 
           y = avg_duration 
       )) +
  
  geom_point(color='red') +
  
  scale_x_log10() +  # Scala logaritmica sull'asse x
  scale_y_log10() +  # Scala logaritmica sull'asse y
  
  labs(title = "Durata vs Lunghezza della stringa",
       x= "Lunghezza della stringa",
       y="Durata (nanosecondi)"
  )

# Creazione del grafico a pallini
ggplot(smart, 
       aes(x = String.Length, 
           y = avg_duration 
       )) +
  scale_x_log10() +  # Scala logaritmica sull'asse x
  scale_y_log10() +  # Scala logaritmica sull'asse y
  
  geom_point(color='blue') +
  
  
  labs(title = "Durata vs Lunghezza della stringa",
       x= "Lunghezza della stringa",
       y="Durata (nanosecondi)",
  )
```


```{r log , echo=FALSE}
##
## display dei primi 20 elementi
##
plot_first_30(naive, "red")
plot_first_30(smart, "blue")


```

```{r reg , echo=FALSE}
delta_time <- data.frame(
  String.Length = naive$String.Length,  # Copia la colonna String.Length da naive
  naive_avg_duration= naive$avg_duration,
  smart_avg_duration= smart$avg_duration,
  avg_delta_duration = naive$avg_duration - smart$avg_duration,  # Calcola la differenza delle durate
  avg_delta_duration_millis = (naive$avg_duration - smart$avg_duration)/ 100000  # millisecondi
)

summary(delta_time)

# Indici delle righe desiderate
indices <- c(1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)

# Seleziona le righe dal dataframe delta_time
selected_rows <- delta_time[indices, ]
print(selected_rows)

```

```{r reg , echo=FALSE}
library(dplyr)

# Raggruppa il dataframe in intervalli di dimensione 10
delta_time_grouped <- delta_time %>%
  mutate(Group = ceiling(row_number() / 5)) %>%
  group_by(Group) %>%
  summarize(
    String.Length = paste(first(String.Length), last(String.Length), sep = "-"),
    
    naive_avg_duration= mean(naive$avg_duration[Group]),
    smart_avg_duration= mean(smart$avg_duration[Group]),
    
    avg_delta_duration = mean(avg_delta_duration),
    avg_delta_duration_millis = mean(avg_delta_duration_millis)
  )

print(delta_time_grouped)


```