---
title: "Periodo frazionario"
author: "Thomas Massarutto"
date: "2023-08-17"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r functions, include=FALSE}
##
## raccolta di funzioni utili
##

library(ggplot2)
library(dplyr)
library(grid)
library(gridExtra)
results <-read.csv("results2.csv")

## plotta una singola run 
smallPlotRun<-function(idRun){
  
  runDataSet= filter(results,Run == idRun)
  
  # Creazione del grafico a pallini
  ggplot(runDataSet, 
         aes(x = String.Length, 
             y = Duration, 
             color = Algorithm.Type)) +
    
    geom_point() +
    
    scale_color_manual(values = c("naive" = "red", 
                                  "smart" = "blue")) +
    
    scale_y_continuous(labels = scales::label_number(scale = 1e-6, suffix = "M"),
                       name = "Nanosecondi") +
    
    scale_x_continuous(labels = scales::label_number(scale = 1e-3, suffix = "K"),
                       name = "Lunghezza stringa") +
    
    theme(legend.position="none")
  
}
#####

## Calcola la media delle run
## ritorna dataset con 2 colonne: string.Length, Duration
## Duration è la media delle run
average <-function(algo){
  # Filtra i risultati per l'algoritmo "naive"
  algo_results <- results %>%
    filter(Algorithm.Type == algo)
  
  # Imposta l'opzione per la notazione esponenziale
  options(scipen = 999)
  
  # Raggruppa per lunghezza della stringa e calcola la media della durata
  average_duration_by_length <- algo_results %>%
    group_by(String.Length) %>%
    summarise(Duration = mean(Duration))
  
  return (average_duration_by_length)
}
#####

# Definizione della funzione per il plot delle prime 20 righe
plot_first_30 <- function(data, point_color) {
  # Prende solo le prime 20 righe
  subset_data <- head(data, 30)
  
  # Creazione del grafico
  ggplot(subset_data, aes(x = String.Length, y = Duration)) +
    geom_point(color = point_color) +
    labs(title = "Primi 30 dati: Durata media vs Lunghezza della stringa",
         x = "Lunghezza della stringa",
         y = "Durata media")
}

```


```{r 6runs , echo=FALSE}
##
## plot delle 5 run di raccolta dati eseguite
##
run1<- smallPlotRun(1)
run2<- smallPlotRun(2)
run3<- smallPlotRun(3)
run4<- smallPlotRun(4)
run5<- smallPlotRun(5)
run6<- smallPlotRun(6)




grid.arrange(run1, run2, run3, run4, run5, run6, 
             ncol = 2, nrow = 3, 
             top=textGrob("Durata vs Lunghezza della stringa"))


```

```{r averagerun, echo=FALSE}
naive <- average("naive")
smart <- average("smart")

# Aggiungi le informazioni calcolate al dataset "results"
results <- bind_rows(
  results,
  mutate(naive, 
         Algorithm.Type =  "naive",
         Fractional.Period = NA,
         Run = 0)
)

results <- bind_rows(
  results,
  mutate(smart, 
         Algorithm.Type =  "smart",
         Fractional.Period = NA,
         Run = 0)
)

## plotta la media
average_results <- filter(results, Run == 0)
ggplot(average_results, 
       aes(x = String.Length, 
           y = Duration, 
           color = Algorithm.Type)) +
  
  geom_point() +
  
  scale_color_manual(values = c("naive" = "red", 
                                "smart" = "blue")) +
  
  scale_x_log10() +  # Scala logaritmica sull'asse x
  scale_y_log10() +  # Scala logaritmica sull'asse y
  
  labs(title = "Durata vs Lunghezza della stringa (scala logaritmica)",
       x= "Lunghezza della stringa (caratteri)",
       y="Durata (nanosecondi)",
       color = "Tipologia di Algoritmo")
```
```{r previsions , echo=FALSE}
# prevedi con regressione

#####

naiveRegression= lm(Duration ~ poly(String.Length, 2, raw=TRUE), data = naive )
coefficenti_naive<-coef(naiveRegression)

ggplot(naive, 
       aes(x = String.Length, 
           y = Duration
       )) +
  
  geom_point(color='red') +
  
stat_smooth( method = "lm", 
             formula = y ~ poly(x, 2, raw = TRUE), 
             se=TRUE, fill=NA,
              colour="black"
             )+

  labs(title = "Durata vs Lunghezza della stringa",
       x= "Lunghezza della stringa",
       y="Durata (nanosecondi)"
  )


#####

smartRegression=lm(Duration ~ String.Length, data = smart)
coefficenti_smart<-coef(smartRegression)

ggplot(smart, 
       aes(x = String.Length, 
           y = Duration
       )) +
  
  geom_point(color='blue') +
  
  geom_smooth(method = "lm",formula = "y ~ x", se = FALSE, color = "black") + 
  
  labs(title = "Durata vs Lunghezza della stringa",
       x= "Lunghezza della stringa",
       y="Durata (nanosecondi)"
  )


```

```{r log , echo=FALSE}
##
## display dei primi 30 elementi
##
plot_first_30(naive, "red")
plot_first_30(smart, "blue")

```

```{r reg2 , echo=FALSE}

# Raggruppa il dataframe in intervalli di dimensione 10
delta_time_grouped <- delta_time %>%
  mutate(Group = ceiling(row_number() / 5)) %>%
  group_by(Group) %>%
  summarize(
    String.Length = paste(first(String.Length), last(String.Length), sep = "-"),
    
    naive_avg_duration= mean(naive$Duration[Group]),
    smart_avg_duration= mean(smart$Duration[Group]),
    
    avg_delta_duration = mean(avg_delta_duration),
    avg_delta_duration_millis = mean(avg_delta_duration_millis)
  )

print(delta_time_grouped)


```